file(WRITE ${OUT_PATH} "<assembly xmlns=\"urn:schemas-microsoft-com:asm.v1\" manifestVersion=\"1.0\">")
foreach(dll IN LISTS DLLS)
  get_filename_component(dll_name ${dll} NAME)
  file(APPEND ${OUT_PATH} "<file name=\"${dll_name}\"></file>")
endforeach()
file(APPEND ${OUT_PATH} "</assembly>")
